on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Compile LateX
        uses: vinay0410/tectonic-action@v1.1.2
        with:
          tex_path: main.tex
          push: "yes" # optional, default is no
